# Generated by Django 4.2.4 on 2023-08-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_description_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_url',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
