# Generated by Django 4.2.4 on 2023-08-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file_url',
            field=models.CharField(max_length=350),
        ),
    ]
